"""Typed identity extras: this app's replacement for a framework user object.

Generated by `fymo generate auth`. fymo answers "who is this request"
(current_uid, an opaque string); everything else about the user is app
data. This module loads your users row once per request scope through the
identity-extras hook and exposes it behind a typed accessor:

    from app.auth.extras import current_extras

    extras = current_extras()          # Extras | None
    if extras is not None:
        greet(extras.email)            # typed, IDE-completable

Extend Extras with whatever your app needs next to the identity (role,
org, plan, ...): add the column, load it in _load_row, add the field.
Extras stay server-side; expose a safe subset to the client yourself
(see me() in app/remote/auth.py).
"""
from dataclasses import dataclass

from fymo.auth import current_uid, identity_extras, register_identity_extras_hook

from app.auth import store


@dataclass(frozen=True)
class Extras:
    email: str
    created_at: str


def _load_row(uid: str) -> dict:
    # Runs at most once per request scope, right after the resolver chain
    # returns a uid. The merged mapping is frozen for the rest of the
    # request; fymo stores it and never inspects it.
    row = store.get_by_id(uid)
    if row is None:
        return {}
    return {"email": row["email"], "created_at": row["created_at"]}


register_identity_extras_hook(_load_row)


def current_extras() -> "Extras | None":
    """Typed view of the signed-in user's row; None when anonymous (or when
    the uid no longer has a row, e.g. a deleted account with a live cookie).
    """
    if current_uid() is None:
        return None
    extras = identity_extras()
    if not extras:
        return None
    return Extras(email=extras["email"], created_at=extras["created_at"])
