"""The public identity projection: what the frontend may know.

Generated by `fymo generate auth`. The mapping returned here is the ONLY
identity data serialized to the client, as the `identity` store in
$fymo/auth (null when anonymous):

    <script>
      import { identity } from '$fymo/auth'
    </script>
    {#if $identity} Hi {$identity.name} {:else} <a href="/signin">Sign in</a> {/if}

Whitelist, never spread: everything returned lands in every page's HTML
for the signed-in user, so add fields one by one and keep secrets and PII
(the email itself, internal ids, roles) out. Server-side data stays in
identity_extras() / app.auth.extras, which never auto-serialize. Without
this file the client would see the safe default, {"uid": ...} only.
"""
from fymo.auth import identity_extras, public_identity


@public_identity
def project(ident):
    # The display name is derived from the email's local part rather than
    # exposing the address itself.
    email = identity_extras().get("email") or ""
    return {"uid": ident.uid, "name": email.split("@", 1)[0] or None}
