-- App-owned users table, generated by `fymo generate auth`.
--
-- This schema is yours: app/auth/store.py applies it idempotently on first
-- connect (CREATE TABLE IF NOT EXISTS never alters an existing table, so
-- evolve a live table with your own ALTER TABLE migrations).
--
-- Deliberately minimal. Columns the old framework-owned fymo_users table
-- carried for its built-in flows are dropped here because no generated code
-- uses them; add them back if you build the flow:
--   email_verified, email_verify_token, email_verify_sent_at  (email verification)
--   password_reset_token                                      (password reset)
--   session_epoch                                             (server-side "log out everywhere")
--   fymo_uid                                                  (legacy anonymous-uid claiming)

CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    email         TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
