"""Session-cookie identity: the resolver plus the cookie's lifecycle.

Generated by `fymo generate auth`. This file is yours: edit it, add more
resolvers, or delete app/auth/ entirely to turn identity resolution off.

fymo auto-discovers app/auth/*.py and each @identify function registers
itself as a resolver. Resolvers run in registration order (module import
order is sorted by filename) and the first one returning an Identity wins;
return None to fall through to the next resolver, or to anonymous.

Everything about the session cookie lives here: its name, how it is
minted (start_session), cleared (end_session), and verified
(by_session_cookie). The remote endpoints in app/remote/auth.py call
start_session/end_session instead of touching the cookie themselves, so
renaming the cookie or changing its lifetime is a one-file edit.
"""
from fymo.auth import Identity, identify, sign_token, verify_token
from fymo.remote import clear_cookie, set_cookie

# The session cookie name; see the module docstring for who mints and
# clears it.
SESSION_COOKIE = "session"

SESSION_MAX_AGE = 7 * 24 * 60 * 60  # seconds; keep <= verify_token's max_age window


def start_session(uid: str) -> None:
    # httpOnly: the browser JS never sees the signed token.
    set_cookie(SESSION_COOKIE, sign_token(uid), max_age=SESSION_MAX_AGE, http_only=True)


def end_session() -> None:
    clear_cookie(SESSION_COOKIE)


@identify
def by_session_cookie(event):
    # event is a fymo.auth.ResolverEvent: .cookies, .headers, .remote_addr,
    # .scheme. The cookie value is a signed token (fymo.auth.sign_token);
    # tampering and expiry both make verify_token return None, so there is
    # no separate error path to handle.
    token = event.cookies.get(SESSION_COOKIE)
    if not token:
        return None
    uid = verify_token(token)
    if uid is None:
        return None
    return Identity(uid=uid)
