"""Test setup (generated by fymo; this file is yours).

Makes the project root importable so tests can `import app.*` no matter
which directory pytest runs from.
"""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
