"""`fymo generate auth`: render app-owned auth code into the project.

Templates are inert text shipped inside the fymo package
(fymo/cli/templates/auth/); fymo never imports them at runtime. Rendering
is a verbatim copy, same spirit as `fymo new`'s inline scaffolds. After
generation the only runtime coupling is auto-discovery: app/auth/*.py for
identity resolvers, app/remote/*.py for the browser-callable endpoints
(the password variant renders its endpoints into app/remote/auth.py so
remote discovery finds them with zero manual wiring).
"""
from pathlib import Path
from typing import List, Optional

from fymo.cli.render import load_template, render
from fymo.cli.writer import PlannedFile, execute_plan
from fymo.utils.colors import Color

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "auth"

_APP_AUTH_INIT = '"""App-owned auth (generated by `fymo generate auth`)."""\n'
_APP_REMOTE_INIT = '"""Remote functions exposed to the browser."""\n'

# variant -> {template relpath: output relpath}
_VARIANT_FILES = {
    "password": {
        "password/resolver.py.tmpl": "app/auth/resolver.py",
        "password/store.py.tmpl": "app/auth/store.py",
        "password/extras.py.tmpl": "app/auth/extras.py",
        "password/public.py.tmpl": "app/auth/public.py",
        "password/remote_auth.py.tmpl": "app/remote/auth.py",
        "password/users.sql.tmpl": "schema/users.sql",
    },
    "clerk": {
        "clerk/resolver.py.tmpl": "app/auth/resolver.py",
    },
    "skeleton": {
        "skeleton/resolver.py.tmpl": "app/auth/resolver.py",
    },
}


def _refuse(message: str) -> None:
    Color.print_error(message)
    raise SystemExit(1)


def _build_plan(root: Path, variant: str) -> List[PlannedFile]:
    """Ordered plan for the variant: package __init__ files first, then the
    rendered templates. app/remote/__init__.py is planned only when the
    variant writes into app/remote/ and the file is not already there (any
    app with remote functions has it, and it is the app's file)."""
    files = _VARIANT_FILES[variant]
    plan = [PlannedFile("app/auth/__init__.py", _APP_AUTH_INIT)]
    remote_init = root / "app" / "remote" / "__init__.py"
    if any(rel.startswith("app/remote/") for rel in files.values()) and not remote_init.exists():
        plan.append(PlannedFile("app/remote/__init__.py", _APP_REMOTE_INIT))
    for tmpl_rel, out_rel in files.items():
        # The auth templates carry no tokens; render({}) is a byte-identical
        # copy and would fail loudly if a marker ever slipped in unrendered.
        # load_template honors a project override at
        # .fymo/templates/auth/<tmpl_rel>, same as every other generator.
        plan.append(PlannedFile(out_rel, render(load_template(root, f"auth/{tmpl_rel}"), {})))
    return plan


def write_auth_files(root: Path, variant: str) -> list:
    """Render the variant's templates into `root`; return the written paths
    (relative). Shared by `fymo generate auth` and `fymo new`; callers own
    any exists/refusal checks."""
    return execute_plan(root, _build_plan(root, variant), command="fymo generate auth",
                        force=True)


def generate_auth(
    variant: str = "password",
    project_root: Optional[Path] = None,
    *,
    force: bool = False,
    dry_run: bool = False,
    diff: bool = False,
) -> None:
    if variant not in _VARIANT_FILES:
        _refuse(f"Unknown auth variant '{variant}'. Use password (default), clerk, or skeleton.")
    root = Path(project_root) if project_root is not None else Path.cwd()

    if not (root / "fymo.yml").is_file():
        _refuse(
            "No fymo.yml here. Run `fymo generate auth` from the project root "
            "(the directory containing fymo.yml)."
        )

    preview = dry_run or diff
    auth_dir = root / "app" / "auth"
    if auth_dir.exists() and not (force or preview):
        _refuse(
            "app/auth/ already exists and `fymo generate auth` never overwrites "
            "it. Delete or move it first (e.g. `mv app/auth app/auth.bak`), "
            "then rerun (or pass --force to overwrite, --diff to preview)."
        )

    if not preview:
        Color.print_info(f"Generating app-owned auth ({variant}) into {root}")
    written = execute_plan(
        root, _build_plan(root, variant), command="fymo generate auth",
        force=force, dry_run=dry_run, diff=diff,
    )
    if preview:
        return

    Color.print_success("Generated:")
    for rel in written:
        print(f"  {rel}")
    _print_next_steps(variant)


def _print_next_steps(variant: str) -> None:
    Color.print_info("\nNext steps:")
    if variant == "password":
        print("  1. Review schema/users.sql. app/auth/store.py applies it on first")
        print("     use and keeps the database at data/app.db (add data/ to .gitignore).")
        print("  2. Create a signin page: add `signin: signin.index` under routes: in")
        print("     fymo.yml, app/controllers/signin.py, and a form in")
        print("     app/templates/signin/index.svelte that calls the login remote")
        print("     function. The route named signin is auto-public and is where")
        print("     anonymous visitors get redirected.")
        print("  3. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml, and remote functions with @fymo.auth.require_auth.")
        print("     signup/login/logout/me in app/remote/auth.py are live remote")
        print("     endpoints already; call them from the browser via the typed")
        print("     $remote client.")
    elif variant == "clerk":
        print("  1. Add pyjwt[crypto]>=2.0 to this app's dependencies and reinstall.")
        print("  2. Set CLERK_ISSUER (or PUBLIC_CLERK_PUBLISHABLE_KEY) in the")
        print("     environment; see app/auth/resolver.py for how it is read.")
        print("  3. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml (add a signin route for the redirect target), and remote")
        print("     functions with @fymo.auth.require_auth.")
    else:
        print("  1. Edit app/auth/resolver.py: make resolve() return")
        print("     Identity(uid=...) for a signed-in request, None for anonymous.")
        print("  2. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml (add a signin route for the redirect target), and remote")
        print("     functions with @fymo.auth.require_auth.")
