"""`fymo generate auth`: render app-owned auth code into the project.

Templates are inert text shipped inside the fymo package
(fymo/cli/templates/auth/); fymo never imports them at runtime. Rendering
is a verbatim copy, same spirit as `fymo new`'s inline scaffolds. After
generation the only runtime coupling is auto-discovery: app/auth/*.py for
identity resolvers, app/remote/*.py for the browser-callable endpoints
(the password variant renders its endpoints into app/remote/auth.py so
remote discovery finds them with zero manual wiring).
"""
from pathlib import Path
from typing import Optional

from fymo.utils.colors import Color

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "auth"

_APP_AUTH_INIT = '"""App-owned auth (generated by `fymo generate auth`)."""\n'
_APP_REMOTE_INIT = '"""Remote functions exposed to the browser."""\n'

# variant -> {template relpath: output relpath}
_VARIANT_FILES = {
    "password": {
        "password/resolver.py.tmpl": "app/auth/resolver.py",
        "password/store.py.tmpl": "app/auth/store.py",
        "password/extras.py.tmpl": "app/auth/extras.py",
        "password/remote_auth.py.tmpl": "app/remote/auth.py",
        "password/users.sql.tmpl": "schema/users.sql",
    },
    "clerk": {
        "clerk/resolver.py.tmpl": "app/auth/resolver.py",
    },
    "skeleton": {
        "skeleton/resolver.py.tmpl": "app/auth/resolver.py",
    },
}


def _refuse(message: str) -> None:
    Color.print_error(message)
    raise SystemExit(1)


def generate_auth(variant: str = "password", project_root: Optional[Path] = None) -> None:
    if variant not in _VARIANT_FILES:
        _refuse(f"Unknown auth variant '{variant}'. Use password (default), clerk, or skeleton.")
    root = Path(project_root) if project_root is not None else Path.cwd()

    if not (root / "fymo.yml").is_file():
        _refuse(
            "No fymo.yml here. Run `fymo generate auth` from the project root "
            "(the directory containing fymo.yml)."
        )

    auth_dir = root / "app" / "auth"
    if auth_dir.exists():
        _refuse(
            "app/auth/ already exists and `fymo generate auth` never overwrites "
            "it. Delete or move it first (e.g. `mv app/auth app/auth.bak`), "
            "then rerun."
        )
    files = _VARIANT_FILES[variant]
    # app/remote/ may legitimately pre-exist (any app with remote functions
    # has it); only the individual output files below may refuse.
    for out_rel in files.values():
        if (root / out_rel).exists():
            _refuse(
                f"{out_rel} already exists and `fymo generate auth` never "
                "overwrites it. Delete or move it first, then rerun."
            )

    Color.print_info(f"Generating app-owned auth ({variant}) into {root}")
    auth_dir.mkdir(parents=True)
    (auth_dir / "__init__.py").write_text(_APP_AUTH_INIT)
    written = ["app/auth/__init__.py"]
    remote_init = root / "app" / "remote" / "__init__.py"
    if any(rel.startswith("app/remote/") for rel in files.values()) and not remote_init.exists():
        remote_init.parent.mkdir(parents=True, exist_ok=True)
        remote_init.write_text(_APP_REMOTE_INIT)
        written.append("app/remote/__init__.py")
    for tmpl_rel, out_rel in files.items():
        out_path = root / out_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text((_TEMPLATES_DIR / tmpl_rel).read_text())
        written.append(out_rel)

    Color.print_success("Generated:")
    for rel in written:
        print(f"  {rel}")
    _print_next_steps(variant)


def _print_next_steps(variant: str) -> None:
    Color.print_info("\nNext steps:")
    if variant == "password":
        print("  1. Review schema/users.sql. app/auth/store.py applies it on first")
        print("     use and keeps the database at data/app.db (add data/ to .gitignore).")
        print("  2. Create a signin page: add `signin: signin.index` under routes: in")
        print("     fymo.yml, app/controllers/signin.py, and a form in")
        print("     app/templates/signin/index.svelte that calls the login remote")
        print("     function. The route named signin is auto-public and is where")
        print("     anonymous visitors get redirected.")
        print("  3. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml, and remote functions with @fymo.auth.require_auth.")
        print("     signup/login/logout/me in app/remote/auth.py are live remote")
        print("     endpoints already; call them from the browser via the typed")
        print("     $remote client.")
    elif variant == "clerk":
        print("  1. Add pyjwt[crypto]>=2.0 to this app's dependencies and reinstall.")
        print("  2. Set CLERK_ISSUER (or PUBLIC_CLERK_PUBLISHABLE_KEY) in the")
        print("     environment; see app/auth/resolver.py for how it is read.")
        print("  3. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml (add a signin route for the redirect target), and remote")
        print("     functions with @fymo.auth.require_auth.")
    else:
        print("  1. Edit app/auth/resolver.py: make resolve() return")
        print("     Identity(uid=...) for a signed-in request, None for anonymous.")
        print("  2. Protect pages with `require_auth: true` on routes/resources in")
        print("     fymo.yml (add a signin route for the redirect target), and remote")
        print("     functions with @fymo.auth.require_auth.")
