"""Auth remote functions: signup, login, logout, me.

Generated by `fymo generate auth`. This is your login flow, edit it: add
email verification, password reset, rate limits (fymo.remote.rate_limit),
whatever your product needs.

This module lives in app/remote/ because remote dispatch only scans
app/remote/*.py; it holds the browser-facing endpoints and nothing else.
The identity home stays in app/auth/ (resolver, store, extras), and these
functions stay thin by delegating to it: storage via app.auth.store,
session cookies via start_session/end_session in app/auth/resolver.py.

Security notes baked in:
  * The session cookie is httpOnly and signed (fymo.auth.sign_token); the
    browser JS never sees the raw token.
  * login accepts a `next` path and answers with a server-driven redirect,
    guarded against open redirects: only local paths pass, anything else
    lands on "/".
  * Failed logins return one generic 401 for both unknown email and wrong
    password (see app/auth/store.py's timing note).
"""
from fymo.auth import current_uid
from fymo.remote import Conflict, Redirect, RemoteError, Unauthorized, remote

from app.auth import store
from app.auth.resolver import end_session, start_session

# Length only, no character-class rules: matches NIST SP 800-63B guidance.
MIN_PASSWORD_LENGTH = 8
# Upper bound so a huge password can't burn CPU in the scrypt hash.
MAX_PASSWORD_LENGTH = 1024


def _validate(email: str, password: str) -> str:
    email = email.strip().lower()
    if not email or "@" not in email or len(email) > 320:
        raise RemoteError("email must be a valid address", status=400, code="bad_input")
    if len(password) < MIN_PASSWORD_LENGTH:
        raise RemoteError(
            f"password must be at least {MIN_PASSWORD_LENGTH} characters",
            status=400, code="bad_input",
        )
    if len(password) > MAX_PASSWORD_LENGTH:
        raise RemoteError(
            f"password must be at most {MAX_PASSWORD_LENGTH} characters",
            status=400, code="bad_input",
        )
    return email


def _safe_next(path: str) -> str:
    # Open-redirect guard: `next` is attacker-controlled. Allow only local
    # paths ("/dashboard"), never protocol-relative ("//evil.example") or
    # absolute ("https://evil.example") targets. Backslashes are rejected
    # anywhere: browsers normalize "\" to "/" in http(s) URLs, so
    # "/\evil.example" would redirect off-site too.
    if path.startswith("/") and not path.startswith("//") and "\\" not in path:
        return path
    return "/"


@remote
def signup(email: str, password: str) -> dict:
    email = _validate(email, password)
    try:
        uid = store.create(email, password)
    except store.EmailAlreadyRegistered:
        raise Conflict("email already registered") from None
    start_session(uid)
    return {"uid": uid, "email": email}


@remote
def login(email: str, password: str, next: str = "/") -> dict:
    email = _validate(email, password)
    uid = store.verify(email, password)
    if uid is None:
        raise Unauthorized("invalid email or password")
    start_session(uid)
    # Server-driven redirect: the $remote client follows the envelope, so
    # the page navigates without the frontend ever handling the token.
    raise Redirect(_safe_next(next))


@remote
def logout() -> dict:
    # The token is stateless, so clearing the cookie is what ends the
    # session in this scaffold. If you need server-side revocation ("log
    # out everywhere"), add an epoch column to users, include it in the
    # uid you sign, and reject stale epochs in app/auth/resolver.py.
    end_session()
    return {"ok": True}


@remote
def me() -> "dict | None":
    """Who am I, as a remote call.

    Templates usually don't need this: the $fymo/auth `identity` store
    already carries the app/auth/public.py projection, hydrated at SSR and
    refreshed on navigation. Kept as the working example of a remote that
    reads current_uid() and returns a whitelisted subset.
    """
    uid = current_uid()
    if uid is None:
        return None
    row = store.get_by_id(uid)
    if row is None:
        return None
    # Only this whitelisted subset ever reaches the client. Never return
    # the row itself: it carries password_hash.
    return {"uid": uid, "email": row["email"], "created_at": row["created_at"]}
