"""Remote functions for comments (generated by `fymo generate remote`; this file is yours).

@remote is what makes a function browser-callable (fymo.yml ships
remote.mode strict, so file placement alone is not enough); after
`fymo build` each one becomes a typed fetch wrapper importable from
'$remote/comments'. The in-memory rows below are stand-in
data: swap them for your real data source and keep the typed signatures.
"""
from typing import Optional, TypedDict

from fymo.auth import require_auth
from fymo.auth import current_uid
from fymo.remote import NotFound, remote


class Comment(TypedDict):
    id: int
    title: str
    created_by: str


_ITEMS: list[Comment] = [
    {"id": 1, "title": "First comment", "created_by": "seed"},
]


def _find(id: int) -> Optional[Comment]:
    return next((row for row in _ITEMS if row["id"] == id), None)


def _owned_or_not_found(id: int) -> Comment:
    # Unknown id and someone else's row answer identically: a 403 on the
    # ownership check would leak that the id exists.
    row = _find(id)
    if row is None or row["created_by"] != current_uid():
        raise NotFound(f"comment {id} not found")
    return row


@remote
def list_comments() -> list[Comment]:
    return list(_ITEMS)


@remote
def get_comment(id: int) -> Comment:
    row = _find(id)
    if row is None:
        raise NotFound(f"comment {id} not found")
    return row


@remote
@require_auth
def create_comment(title: str) -> Comment:
    # The author comes from the authenticated identity, never client input.
    item: Comment = {
        "id": max((row["id"] for row in _ITEMS), default=0) + 1,
        "title": title,
        "created_by": current_uid(),
    }
    _ITEMS.append(item)
    return item


@remote
@require_auth
def update_comment(id: int, title: str) -> Comment:
    row = _owned_or_not_found(id)
    row["title"] = title
    return row


@remote
@require_auth
def delete_comment(id: int) -> Comment:
    row = _owned_or_not_found(id)
    _ITEMS.remove(row)
    return row
